"""schema inicial

Revision ID: 3a53e39a7183
Revises: 
Create Date: 2026-06-11 22:43:38.081742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a53e39a7183'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('codigo_convite', sa.String(length=10), nullable=True),
    sa.Column('aceitou_termos_em', sa.DateTime(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_codigo_convite'), ['codigo_convite'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('arquivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutricionista_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_armazenado', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('visto_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_armazenado')
    )
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arquivos_nutricionista_id'), ['nutricionista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arquivos_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('exercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('atividade', sa.String(length=80), nullable=True),
    sa.Column('duracao_minutos', sa.Float(), nullable=False),
    sa.Column('intensidade', sa.Integer(), nullable=True),
    sa.Column('sentimento_apos', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercicios_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercicios_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('refeicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('alimentos', sa.Text(), nullable=True),
    sa.Column('fome_antes', sa.Integer(), nullable=False),
    sa.Column('saciedade_antes', sa.Integer(), nullable=False),
    sa.Column('fome_depois', sa.Integer(), nullable=False),
    sa.Column('saciedade_depois', sa.Integer(), nullable=False),
    sa.Column('sentimento_antes', sa.String(length=40), nullable=True),
    sa.Column('sentimento_durante', sa.String(length=40), nullable=True),
    sa.Column('local_refeicao', sa.String(length=40), nullable=True),
    sa.Column('companhia', sa.String(length=40), nullable=True),
    sa.Column('tempo_refeicao', sa.Integer(), nullable=True),
    sa.Column('agua_ml', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refeicoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refeicoes_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_refeicoes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_dormir', sa.String(length=5), nullable=False),
    sa.Column('hora_acordar', sa.String(length=5), nullable=False),
    sa.Column('duracao_horas', sa.Float(), nullable=True),
    sa.Column('qualidade', sa.Integer(), nullable=True),
    sa.Column('como_acordou', sa.String(length=40), nullable=True),
    sa.Column('interrupcoes', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sono', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sono_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_sono_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('vinculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutricionista_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutricionista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nutricionista_id', 'paciente_id')
    )
    with op.batch_alter_table('vinculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vinculos_nutricionista_id'), ['nutricionista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vinculos_paciente_id'), ['paciente_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vinculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vinculos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_vinculos_nutricionista_id'))

    op.drop_table('vinculos')
    with op.batch_alter_table('sono', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sono_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_sono_data'))

    op.drop_table('sono')
    with op.batch_alter_table('refeicoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refeicoes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_refeicoes_data_hora'))

    op.drop_table('refeicoes')
    with op.batch_alter_table('exercicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercicios_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_exercicios_data'))

    op.drop_table('exercicios')
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arquivos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_arquivos_nutricionista_id'))

    op.drop_table('arquivos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_codigo_convite'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
